name: Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write
  packages: write

jobs:
  push-docker-image:
    uses: ./.github/workflows/push-docker-image.yml
    secrets: inherit