name: Pull Request Workflow

on:
  pull_request_target:

jobs:
  lint-format:
    uses: ./.github/workflows/lint-format.yml
  unit-sec-scan:
    uses: ./.github/workflows/unit-sec-test.yml
    needs: lint-format
