name: Push Docker Image - GitHub Container Registry (GHCR)

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "the-herald"

jobs:
  Push_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

        # Extract metadata (tags, labels) for Docker
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and tag Docker Image
      - name: Build & Push Multi-Arch Docker Image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest \
          --push \
          .